server:
  port: 8085
spring:
  config:
    activate:
      on-profile: local
  application:
    name: report-service
  scheduler:
    cron: 0 10 * * *
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
